<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=shift-jis">
  <title>エラー処理</title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="sca.examples.structures.html">≪ データ構造の扱い</a></li>
      <li style="float: right;"><a href="ref.sca.html">SCA 関数 ≫</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="sca.examples.html">例</a></li>
    <li>エラー処理</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="sca.examples.errorhandling" class="section">
  <h2 class="title">エラー処理</h2>
  <p class="para"> 
   この節では、エラーの処理方法について説明します。
   エラーには次の二種類があります。
  </p>
  <ul class="itemizedlist">
   <li class="listitem">
    <p class="para"> 
     SCA の実行時例外。これは、
     コンポーネントの実行やリモートサービスとのやりとりの際に問題が発生したことを表すものです。
     ネットワークや設定の問題が原因で起こることがあります。
    </p>
   </li>
   
   <li class="listitem">
    <p class="para"> 
     ビジネスロジックの例外。これは、
     プログラマが定義するものです。
     PHP の Exception クラスを継承したクラスを作成し、
     ビジネスロジックで問題が発生した場合に故意にスローします。
    </p>
   </li>
   
  </ul>
  
  <div class="section" id="sca.examples.errorhandling.runtime">
   <h2 class="title">実行時例外の処理</h2>
   <p class="para"> 
    SCA の実行時例外には二つの型があります。
   </p>
   
   <ul class="itemizedlist">
    <li class="listitem">
     <p class="para"> 
      SCA_RuntimeException -
      SCA ランタイム内で問題が見つかった、あるいは問題が起こったであろうと考えられるということを通知します。
      これは、さまざまな理由で発生しえます。
      その多くは、対象がローカルであるかリモートサービスであるかにかかわらず発生します。
      コンポーネント内のアノテーションのエラーや、
      WSDL や PHP ファイルが存在しないなどといった内容です。
      ウェブサービスの場合に SCA_RuntimeException がスローされるのは、
      リモートのウェブサービスから SoapFault を受け取り、
      その失敗コードの内容が「再試行しても成功しないであろう」と判断されるときです。
     </p>
    </li>
    
    <li class="listitem">
     <p class="para"> 
      SCA_ServiceUnavailableException -
      これは SCA_RuntimeException のサブクラスです。
      接続時やリモートサービスの使用時に問題が発生したものの、
      再試行すれば成功する可能性がある場合にスローされます。
      ウェブサービスの場合にこの例外がスローされるのは、
      リモートのウェブサービスから SoapFault を受け取り、
      その失敗コードの内容が「再試行すれば成功するであろう」と判断されるときです。
     </p>
    </li>
    
   </ul>
  </div>
  
  <div class="section" id="sca.examples.errorhandlilng.business"> 
   <h2 class="title">ビジネスロジックの例外の処理</h2>
   <p class="para"> 
    ビジネスロジックの例外の定義やスローは、通常通りの方法でコンポーネントで行います。
    そのコンポーネントがローカルにコールされるかリモートからコールされるかは関係ありません。
    SCA ランタイムは、ローカルからコールされたコンポーネント内で発生した
    ビジネスロジック例外をキャッチしません。これは呼び出し元に返されます。
    一方、コンポーネントがウェブサービス経由でコールされた場合は
    SCA ランタイムがそのビジネスロジック例外をキャッチし、再度スローします。
    呼び出し元がその例外の定義を知っている
    (その例外の PHP クラス定義を含むファイルをインクルードしている)
    ものとして、再度スローされた冷害は元の例外と同じ内容を含みます。
    つまり、たとえば
    <span class="function"><strong>getLine()</strong></span> メソッドや
    <span class="function"><strong>getFile()</strong></span> メソッドには
    ビジネスロジック内のどの位置で例外が発生したのかが含まれます。
    例外は、soap fault の詳細フィールドにおいて &quot;Client&quot;
    というコードで渡されます。
   </p>
  </div>
  
    
 </div><div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
 <div class="note">There are no user contributed notes for this page.</div>
</div>
</div></div></body></html>
