<html><!-- Mirrored from php.net/manual/en/function.set-exception-handler.php by HTTrack Website Copier/3.x [XR&CO'2013], Thu, 28 Aug 2014 15:28:43 GMT --><!-- Added by HTTrack --><head><meta http-equiv="content-type" content="text/html;charset=utf-8"><!-- /Added by HTTrack -->


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 

  <title>set_exception_handler</title>

 <link rel="shortcut icon" href="../../favicon.ico">
 <link rel="search" type="application/opensearchdescription+xml" href="http://php.net/phpnetimprovedsearch.src" title="Add PHP.net search">
 <link rel="alternate" type="application/atom+xml" href="http://php.net/releases/feed.php" title="PHP Release feed">
 <link rel="alternate" type="application/atom+xml" href="http://php.net/feed.atom" title="PHP: Hypertext Preprocessor">

 <link rel="canonical" href="function.set-exception-handler.html">
 <link rel="shorturl" href="http://php.net/set-exception-handler">
 <link rel="alternate" href="http://php.net/set-exception-handler" hreflang="x-default">

 <link rel="contents" href="index-2.html">
 <link rel="index" href="ref.errorfunc.html">
 <link rel="prev" href="function.set-error-handler.html">
 <link rel="next" href="function.trigger-error.html">

 <link rel="alternate" href="function.set-exception-handler.html" hreflang="en">
 <link rel="alternate" href="http://php.net/manual/pt_BR/function.set-exception-handler.php" hreflang="pt_BR">
 <link rel="alternate" href="http://php.net/manual/zh/function.set-exception-handler.php" hreflang="zh">
 <link rel="alternate" href="http://php.net/manual/fr/function.set-exception-handler.php" hreflang="fr">
 <link rel="alternate" href="http://php.net/manual/de/function.set-exception-handler.php" hreflang="de">
 <link rel="alternate" href="http://php.net/manual/it/function.set-exception-handler.php" hreflang="it">
 <link rel="alternate" href="http://php.net/manual/ja/function.set-exception-handler.php" hreflang="ja">
 <link rel="alternate" href="http://php.net/manual/ro/function.set-exception-handler.php" hreflang="ro">
 <link rel="alternate" href="http://php.net/manual/ru/function.set-exception-handler.php" hreflang="ru">
 <link rel="alternate" href="http://php.net/manual/es/function.set-exception-handler.php" hreflang="es">
 <link rel="alternate" href="http://php.net/manual/tr/function.set-exception-handler.php" hreflang="tr">

<link rel="stylesheet" type="text/css" href="../../cached8fe1.css?t=1401250819&amp;f=/fonts/Fira/fira.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached4b8d.css?t=1404368420&amp;f=/fonts/Font-Awesome/css/fontello.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cached5065.css?t=1403329232&amp;f=/styles/theme-base.css" media="screen">
<link rel="stylesheet" type="text/css" href="../../cachedc78d.css?t=1401249623&amp;f=/styles/theme-medium.css" media="screen">

 <!--[if lte IE 7]>
 <link rel="stylesheet" type="text/css" href="http://php.net/styles/workarounds.ie7.css" media="screen">
 <![endif]-->

 <!--[if lte IE 8]>
 <script type="text/javascript">
  window.brokenIE = true;
 </script>
 <![endif]-->

 <!--[if lte IE 9]>
 <link rel="stylesheet" type="text/css" href="http://php.net/styles/workarounds.ie9.css" media="screen">
 <![endif]-->

 <!--[if IE]>
 <script type="text/javascript" src="http://php.net/js/ext/html5.js"></script>
 <![endif]-->

 <base>

</head>
<body class="docs " style="">


<div class="headsup"><a href="http://php.net/index.php#id2014-08-28-1">PHP 5.6.0 released</a></div>
<nav id="trick"><div><dl>
<dt><a href="getting-started.html">Getting Started</a></dt>
	<dd><a href="introduction.html">Introduction</a></dd>
	<dd><a href="tutorial.html">A simple tutorial</a></dd>
<dt><a href="langref.html">Language Reference</a></dt>
	<dd><a href="language.basic-syntax.html">Basic syntax</a></dd>
	<dd><a href="language.types.html">Types</a></dd>
	<dd><a href="language.variables.html">Variables</a></dd>
	<dd><a href="language.constants.html">Constants</a></dd>
	<dd><a href="language.expressions.html">Expressions</a></dd>
	<dd><a href="language.operators.html">Operators</a></dd>
	<dd><a href="language.control-structures.html">Control Structures</a></dd>
	<dd><a href="language.functions.html">Functions</a></dd>
	<dd><a href="language.oop5.html">Classes and Objects</a></dd>
	<dd><a href="language.namespaces.html">Namespaces</a></dd>
	<dd><a href="language.exceptions.html">Exceptions</a></dd>
	<dd><a href="language.generators.html">Generators</a></dd>
	<dd><a href="language.references.html">References Explained</a></dd>
	<dd><a href="reserved.variables.html">Predefined Variables</a></dd>
	<dd><a href="reserved.exceptions.html">Predefined Exceptions</a></dd>
	<dd><a href="reserved.interfaces.html">Predefined Interfaces and Classes</a></dd>
	<dd><a href="context.html">Context options and parameters</a></dd>
	<dd><a href="wrappers.html">Supported Protocols and Wrappers</a></dd>
</dl>
<dl>
<dt><a href="security.html">Security</a></dt>
	<dd><a href="security.intro.html">Introduction</a></dd>
	<dd><a href="security.general.html">General considerations</a></dd>
	<dd><a href="security.cgi-bin.html">Installed as CGI binary</a></dd>
	<dd><a href="security.apache.html">Installed as an Apache module</a></dd>
	<dd><a href="security.filesystem.html">Filesystem Security</a></dd>
	<dd><a href="security.database.html">Database Security</a></dd>
	<dd><a href="security.errors.html">Error Reporting</a></dd>
	<dd><a href="security.globals.html">Using Register Globals</a></dd>
	<dd><a href="security.variables.html">User Submitted Data</a></dd>
	<dd><a href="security.magicquotes.html">Magic Quotes</a></dd>
	<dd><a href="security.hiding.html">Hiding PHP</a></dd>
	<dd><a href="security.current.html">Keeping Current</a></dd>
<dt><a href="features.html">Features</a></dt>
	<dd><a href="features.http-auth.html">HTTP authentication with PHP</a></dd>
	<dd><a href="features.cookies.html">Cookies</a></dd>
	<dd><a href="features.sessions.html">Sessions</a></dd>
	<dd><a href="features.xforms.html">Dealing with XForms</a></dd>
	<dd><a href="features.file-upload.html">Handling file uploads</a></dd>
	<dd><a href="features.remote-files.html">Using remote files</a></dd>
	<dd><a href="features.connection-handling.html">Connection handling</a></dd>
	<dd><a href="features.persistent-connections.html">Persistent Database Connections</a></dd>
	<dd><a href="features.safe-mode.html">Safe Mode</a></dd>
	<dd><a href="features.commandline.html">Command line usage</a></dd>
	<dd><a href="features.gc.html">Garbage Collection</a></dd>
	<dd><a href="features.dtrace.html">DTrace Dynamic Tracing</a></dd>
</dl>
<dl>
<dt><a href="funcref.html">Function Reference</a></dt>
	<dd><a href="refs.basic.php.html">Affecting PHP's Behaviour</a></dd>
	<dd><a href="refs.utilspec.audio.html">Audio Formats Manipulation</a></dd>
	<dd><a href="refs.remote.auth.html">Authentication Services</a></dd>
	<dd><a href="refs.utilspec.cmdline.html">Command Line Specific Extensions</a></dd>
	<dd><a href="refs.compression.html">Compression and Archive Extensions</a></dd>
	<dd><a href="refs.creditcard.html">Credit Card Processing</a></dd>
	<dd><a href="refs.crypto.html">Cryptography Extensions</a></dd>
	<dd><a href="refs.database.html">Database Extensions</a></dd>
	<dd><a href="refs.calendar.html">Date and Time Related Extensions</a></dd>
	<dd><a href="refs.fileprocess.file.html">File System Related Extensions</a></dd>
	<dd><a href="refs.international.html">Human Language and Character Encoding Support</a></dd>
	<dd><a href="refs.utilspec.image.html">Image Processing and Generation</a></dd>
	<dd><a href="refs.remote.mail.html">Mail Related Extensions</a></dd>
	<dd><a href="refs.math.html">Mathematical Extensions</a></dd>
	<dd><a href="refs.utilspec.nontext.html">Non-Text MIME Output</a></dd>
	<dd><a href="refs.fileprocess.process.html">Process Control Extensions</a></dd>
	<dd><a href="refs.basic.other.html">Other Basic Extensions</a></dd>
	<dd><a href="refs.remote.other.html">Other Services</a></dd>
	<dd><a href="refs.search.html">Search Engine Extensions</a></dd>
	<dd><a href="refs.utilspec.server.html">Server Specific Extensions</a></dd>
	<dd><a href="refs.basic.session.html">Session Extensions</a></dd>
	<dd><a href="refs.basic.text.html">Text Processing</a></dd>
	<dd><a href="refs.basic.vartype.html">Variable and Type Related Extensions</a></dd>
	<dd><a href="refs.webservice.html">Web Services</a></dd>
	<dd><a href="refs.utilspec.windows.html">Windows Only Extensions</a></dd>
	<dd><a href="refs.xml.html">XML Manipulation</a></dd>
</dl>
<dl>
<dt>Keyboard Shortcuts</dt><dt>?</dt>
<dd>This help</dd>
<dt>j</dt>
<dd>Next menu item</dd>
<dt>k</dt>
<dd>Previous menu item</dd>
<dt>g p</dt>
<dd>Previous man page</dd>
<dt>g n</dt>
<dd>Next man page</dd>
<dt>G</dt>
<dd>Scroll to bottom</dd>
<dt>g g</dt>
<dd>Scroll to top</dd>
<dt>g h</dt>
<dd>Goto homepage</dd>
<dt>g s</dt>
<dd>Goto search<br>(current page)</dd>
<dt>/</dt>
<dd>Focus search box</dd>
</dl></div></nav>
<div id="goto">
    <div class="search">
         <div class="text"></div>
         <div class="results"><ul></ul></div>
   </div>
</div>

  <div id="breadcrumbs" class="row-fluid">
          
              
        <ul class="breadcrumbs-container">
            <li><a href="index-2.html">PHP Manual</a></li>      <li><a href="funcref.html">Function Reference</a></li>      <li><a href="refs.basic.php.html">Affecting PHP's Behaviour</a></li>      <li><a href="book.errorfunc.html">Error Handling</a></li>      <li><a href="ref.errorfunc.html">Error Handling Functions</a></li>    </ul>
  </div>




<div id="layout">
  <section id="layout-content">
  <div id="function.set-exception-handler" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">set_exception_handler</h1>
  <p class="verinfo">(PHP 5)</p><p class="refpurpose"><span class="refname">set_exception_handler</span> â€” <span class="dc-title">
   Sets a user-defined exception handler function 
  </span></p>

 </div>

 <div class="refsect1 description" id="refsect1-function.set-exception-handler-description">
  <h3 class="title">Description</h3>
  <div class="methodsynopsis dc-description">
   <span class="type"><a href="language.types.callable.html" class="type callable">callable</a></span> <span class="methodname"><strong>set_exception_handler</strong></span>
    ( <span class="methodparam"><span class="type"><a href="language.types.callable.html" class="type callable">callable</a></span> <code class="parameter">$exception_handler</code></span>
   )</div>

  <p class="para rdfs-comment">
   Sets the default exception handler if an exception is not caught within a
   try/catch block. Execution will stop after the
   <code class="parameter">exception_handler</code> is called.
  </p>
 </div>


 <div class="refsect1 parameters" id="refsect1-function.set-exception-handler-parameters">
  <h3 class="title">Parameters</h3>
  <p class="para">
   </p><dl>

    
     <dt>
<code class="parameter">exception_handler</code></dt>

     <dd>

      <p class="para">
       Name of the function to be called when an uncaught exception occurs.
       This handler function
       needs to accept one parameter, which will be the exception object that
       was thrown. This is the handler signature:
      </p>
      <p class="para">
       </p><div class="methodsynopsis dc-description">
        <span class="type"><span class="type void">void</span></span> <span class="methodname"><span class="replaceable">handler</span></span>
         ( <span class="methodparam"><span class="type"><a href="class.exception.html" class="type Exception">Exception</a></span> <code class="parameter">$ex</code></span>
        )</div>

      <p></p>
      <p class="para">
       <strong><code>NULL</code></strong> may be passed instead, to reset this handler to its default state.
      </p>
     </dd>

    
   </dl>

  <p></p>
 </div>


 <div class="refsect1 returnvalues" id="refsect1-function.set-exception-handler-returnvalues">
  <h3 class="title">Return Values</h3>
  <p class="para">
   Returns the name of the previously defined exception handler, or <strong><code>NULL</code></strong> on error. If
   no previous handler was defined, <strong><code>NULL</code></strong> is also returned.
  </p>
 </div>


 <div class="refsect1 changelog" id="refsect1-function.set-exception-handler-changelog">
  <h3 class="title">Changelog</h3>
  <p class="para">
   </p><table class="doctable informaltable">
    
     <thead>
      <tr>
       <th>Version</th>
       <th>Description</th>
      </tr>

     </thead>

     <tbody class="tbody">
      <tr>
       <td>5.5.0</td>
       <td>
        Previously, if <strong><code>NULL</code></strong> was passed then this function returned <strong><code>TRUE</code></strong>.
        It returns the previous handler since PHP 5.5.0.
       </td>
      </tr>

     </tbody>
    
   </table>

  <p></p>
 </div>


 <div class="refsect1 examples" id="refsect1-function.set-exception-handler-examples">
  <h3 class="title">Examples</h3>
  <p class="para">
   </p><div class="example" id="example-476">
    <p><strong>Example #1 <span class="function"><strong>set_exception_handler()</strong></span> example</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br></span><span style="color: #007700">function&nbsp;</span><span style="color: #0000BB">exception_handler</span><span style="color: #007700">(</span><span style="color: #0000BB">$exception</span><span style="color: #007700">)&nbsp;{<br>&nbsp;&nbsp;echo&nbsp;</span><span style="color: #DD0000">"Uncaught&nbsp;exception:&nbsp;"&nbsp;</span><span style="color: #007700">,&nbsp;</span><span style="color: #0000BB">$exception</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(),&nbsp;</span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br>}<br><br></span><span style="color: #0000BB">set_exception_handler</span><span style="color: #007700">(</span><span style="color: #DD0000">'exception_handler'</span><span style="color: #007700">);<br><br>throw&nbsp;new&nbsp;</span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Uncaught&nbsp;Exception'</span><span style="color: #007700">);<br>echo&nbsp;</span><span style="color: #DD0000">"Not&nbsp;Executed\n"</span><span style="color: #007700">;<br></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

   </div>
  <p></p>
 </div>


 <div class="refsect1 seealso" id="refsect1-function.set-exception-handler-seealso">
  <h3 class="title">See Also</h3>
  <p class="para">
   </p><ul class="simplelist">
    <li class="member"><span class="function"><a href="function.restore-exception-handler.html" class="function" rel="rdfs-seeAlso">restore_exception_handler()</a> - Restores the previously defined exception handler function</span></li>
    <li class="member"><span class="function"><a href="function.restore-error-handler.html" class="function" rel="rdfs-seeAlso">restore_error_handler()</a> - Restores the previous error handler function</span></li>
    <li class="member"><span class="function"><a href="function.error-reporting.html" class="function" rel="rdfs-seeAlso">error_reporting()</a> - Sets which PHP errors are reported</span></li>
    <li class="member">information about the <a href="language.pseudo-types.html#language.types.callback" class="link">callback</a> type</li>
    <li class="member"><a href="language.exceptions.html" class="link">PHP 5 Exceptions</a></li>
   </ul>
  <p></p>
 </div>


</div>
<section id="usernotes">
 <div class="head"><h3 class="title">User Contributed Notes</h3></div><div id="allnotes">
  <div class="note" id="95170">  
  <a class="name">
  <strong class="user"><em>Anonymous</em></strong></a><div class="date" title="2009-12-16 06:12"><strong>4 years ago</strong></div>
  <div class="text" id="Hcom95170">
<div class="phpcode"><code><span class="html">
Things you should be aware of:<br><br>An exception handler handles exceptions that were not caught before. It is the nature of an exception that it discontinues execution of your program - since it declares an exceptional situation in which the program cannot continue (except you catch it).<br><br>Since it has not been catched your code signals it is not being aware of the situation and cant go on.<br><br>This implies: returning to the script is simply impossible when the exception handler has already been called, since an uncaught exception is not a notice. use your own debug- or notice-log-system for things like that.<br><br>Furthermore: While is is still possible to call functions from your script, since the exception handler has already been called exceptions bubbling from that piece of code won't trigger the exception handler again. php will die without leaving any information apart form "uncaught exception with unknown stack frame". So if you call functions from your script, make sure that you catch any exceptions that possibly occur via try..catch inside the exception handler.<br><br>For those of you who misinterpreted the essential meaning of the exception handler: it's only use is to handle the abortion of your script gracefully, e.g. in a project like facebook or wikipedia: render a nice error page, eventually hiding information which shall not leak into the public (instead you may want to write to your log or mail the sys-admin or stuff like that).<br><br>In other words: Redirecting all php-errors form an error-handler using exceptions - including notices - is a very dumb idea, if you do not intend having your script aborted everytime you didn't set a variable (for example).<br><br>my 2 cents.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="88082">  
  <a class="name">
  <strong class="user"><em>joshua dot boyle-petrie at its dot monash dot edu</em></strong></a><div class="date" title="2009-01-08 11:44"><strong>5 years ago</strong></div>
  <div class="text" id="Hcom88082">
<div class="phpcode"><code><span class="html">
Thanks to mastabog we know that throwing an exception within the exception handler will trigger a fatal error and a debugging nightmare.&nbsp; To avoid throwing an exception within there should be easy.<br><br>However, if you use a custom error handler to convert errors to ErrorExceptions suddenly there are a multitude of new ways to accidentally throw exceptions within the exception handler.<br><br><span class="default">&lt;?php<br></span><span class="keyword">function </span><span class="default">error_handler</span><span class="keyword">(</span><span class="default">$code</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">)<br>{<br>&nbsp; &nbsp; if (</span><span class="default">0 </span><span class="keyword">== </span><span class="default">error_reporting</span><span class="keyword">())<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; return;<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">);<br>}<br>function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">)<br>{<br>&nbsp; &nbsp; </span><span class="comment">// ... normal exception stuff goes here<br>&nbsp; &nbsp; </span><span class="keyword">print </span><span class="default">$undefined</span><span class="keyword">; </span><span class="comment">// This is the underlying problem<br></span><span class="keyword">}<br></span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">"error_handler"</span><span class="keyword">);<br></span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"exception_handler"</span><span class="keyword">);<br>throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Just invoking the exception handler"</span><span class="keyword">);<br></span><span class="default">?&gt;<br></span>Output: Fatal error: Exception thrown without a stack frame in Unknown on line 0<br><br>The best way I have found to avoid this is to wrap up everything in the exception handler in a try/catch block.<br><span class="default">&lt;?php<br></span><span class="keyword">function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">)<br>{<br>&nbsp; &nbsp; try<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// ... normal exception stuff goes here<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="keyword">print </span><span class="default">$undefined</span><span class="keyword">; </span><span class="comment">// This is the underlying problem<br>&nbsp; &nbsp; </span><span class="keyword">}<br>&nbsp; &nbsp; catch (</span><span class="default">Exception $e</span><span class="keyword">)<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; print </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">).</span><span class="string">" thrown within the exception handler. Message: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" on line "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">();<br>&nbsp; &nbsp; }<br>}<br></span><span class="default">?&gt;<br></span>Output: ErrorException thrown within the exception handler. Message: Undefined variable: undefined on line 14<br><br>This speeds up debugging and offers some scalability to any other exceptions accidentally thrown within the exception handler.<br><br>Another solution is to restore the error handler at the beginning of the exception handler.&nbsp; While this is a silver bullet in terms of avoiding the ErrorExceptions, debugging messages then rely on the error_reporting() level and the display_errors directive.&nbsp; Why mention this?&nbsp; It might be preferable for production code since we care more about hiding errors from users than convenient debugging messages.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="98201">  
  <a class="name">
  <strong class="user"><em>pinkgothic at gmail dot com</em></strong></a><div class="date" title="2010-06-01 02:30"><strong>4 years ago</strong></div>
  <div class="text" id="Hcom98201">
<div class="phpcode"><code><span class="html">
If you're handling sensitive data and you don't want exceptions logging details such as variable contents when you throw them, you may find yourself frustratedly looking for the bits and pieces that make up a normal stack trace output, so you can retain its legibility but just alter a few things. In that case, this may help you:<br><br><span class="default">&lt;?php<br><br></span><span class="keyword">function </span><span class="default">exceptionHandler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br><br>&nbsp; &nbsp; </span><span class="comment">// these are our templates<br>&nbsp; &nbsp; </span><span class="default">$traceline </span><span class="keyword">= </span><span class="string">"#%s %s(%s): %s(%s)"</span><span class="keyword">;<br>&nbsp; &nbsp; </span><span class="default">$msg </span><span class="keyword">= </span><span class="string">"PHP Fatal error:&nbsp; Uncaught exception '%s' with message '%s' in %s:%s\nStack trace:\n%s\n&nbsp; thrown in %s on line %s"</span><span class="keyword">;<br><br>&nbsp; &nbsp; </span><span class="comment">// alter your trace as you please, here<br>&nbsp; &nbsp; </span><span class="default">$trace </span><span class="keyword">= </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getTrace</span><span class="keyword">();<br>&nbsp; &nbsp; foreach (</span><span class="default">$trace </span><span class="keyword">as </span><span class="default">$key </span><span class="keyword">=&gt; </span><span class="default">$stackPoint</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">// I'm converting arguments to their type<br>&nbsp; &nbsp; &nbsp; &nbsp; // (prevents passwords from ever getting logged as anything other than 'string')<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$trace</span><span class="keyword">[</span><span class="default">$key</span><span class="keyword">][</span><span class="string">'args'</span><span class="keyword">] = </span><span class="default">array_map</span><span class="keyword">(</span><span class="string">'gettype'</span><span class="keyword">, </span><span class="default">$trace</span><span class="keyword">[</span><span class="default">$key</span><span class="keyword">][</span><span class="string">'args'</span><span class="keyword">]);<br>&nbsp; &nbsp; }<br><br>&nbsp; &nbsp; </span><span class="comment">// build your tracelines<br>&nbsp; &nbsp; </span><span class="default">$result </span><span class="keyword">= array();<br>&nbsp; &nbsp; foreach (</span><span class="default">$trace </span><span class="keyword">as </span><span class="default">$key </span><span class="keyword">=&gt; </span><span class="default">$stackPoint</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$result</span><span class="keyword">[] = </span><span class="default">sprintf</span><span class="keyword">(<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$traceline</span><span class="keyword">,<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$key</span><span class="keyword">,<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'file'</span><span class="keyword">],<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'line'</span><span class="keyword">],<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'function'</span><span class="keyword">],<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">implode</span><span class="keyword">(</span><span class="string">', '</span><span class="keyword">, </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'args'</span><span class="keyword">])<br>&nbsp; &nbsp; &nbsp; &nbsp; );<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; </span><span class="comment">// trace always ends with {main}<br>&nbsp; &nbsp; </span><span class="default">$result</span><span class="keyword">[] = </span><span class="string">'#' </span><span class="keyword">. ++</span><span class="default">$key </span><span class="keyword">. </span><span class="string">' {main}'</span><span class="keyword">;<br><br>&nbsp; &nbsp; </span><span class="comment">// write tracelines into main template<br>&nbsp; &nbsp; </span><span class="default">$msg </span><span class="keyword">= </span><span class="default">sprintf</span><span class="keyword">(<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$msg</span><span class="keyword">,<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">),<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">(),<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getFile</span><span class="keyword">(),<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">(),<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">implode</span><span class="keyword">(</span><span class="string">"\n"</span><span class="keyword">, </span><span class="default">$result</span><span class="keyword">),<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getFile</span><span class="keyword">(),<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">()<br>&nbsp; &nbsp; );<br><br>&nbsp; &nbsp; </span><span class="comment">// log or echo as you please<br>&nbsp; &nbsp; </span><span class="default">error_log</span><span class="keyword">(</span><span class="default">$msg</span><span class="keyword">);<br>}<br><br></span><span class="default">?&gt;<br></span><br>If you're not a fan of sprintf() or the duplicate $exception-&gt;getFile() and $exception-&gt;getLine() calls you can of course replace that as you like - consider this a mere compilation of the parts.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="68712">  
  <a class="name">
  <strong class="user"><em>mastabog at hotmail dot com</em></strong></a><div class="date" title="2006-08-08 07:44"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom68712">
<div class="phpcode"><code><span class="html">
A behaviour not documented or discussed enough, yet pretty common is that is that if an exception is thrown from the global exception handler then a fatal error occurs (Exception thrown without a stack frame). That is, if you define your own global exception handler by calling set_exception_handler() and you throw an exception from inside it then this fatal error occurs. It is only natural though, as the callback defined by set_exception_handler() is only called on uncaught (unhandled) exceptions so if you throw one from there then you get this fatal error as there is no exception handler left (you override the php internal one by calling set_exception_handler()), hence no stack frame for it.<br><br>Example:<br><br><span class="default">&lt;?php<br><br></span><span class="keyword">function </span><span class="default">myExceptionHandler </span><span class="keyword">(</span><span class="default">Exception $ex</span><span class="keyword">)<br>{<br>&nbsp; &nbsp; throw </span><span class="default">$ex</span><span class="keyword">;<br>}<br><br></span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"myExceptionHandler"</span><span class="keyword">);<br><br>throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"This should cause a fatal error and this message will be lost"</span><span class="keyword">);<br><br></span><span class="default">?&gt;<br></span><br>Will cause a Fatal error: Exception thrown without a stack frame<br><br>If you skip/comment the set_exception_handler("...") line then the internal PHP global handler will catch the exception and output the exception message and trace (as string) to the browser, allowing you to at least see the exception message.<br><br>While it is a very good idea to always define your own global exception handler by using the set_exception_handler() function, you should pay attention and never throw an exception from it (or if you do then catch it).<br><br>Finally, every serious coder should use an IDE with debugging capabilities. Tracking down an error like this becomes a trivial matter by using simple debugging "Step into" commands (I for one recommend Zend IDE v5.2 at the moment of this writing). I have seen numerous messages on the internet with people wondering why this message pops up.<br><br>Cheers<br><br>p.s. Other causes for this error which are somehow unrelated to this is when you throw an exception from a destructor (the reasons behind that are similar though, the global handler might no longer exist due to the php engine shutting the page down).</span>
</code></div>
  </div>
 </div>
  <div class="note" id="114582">  
  <a class="name">
  <strong class="user"><em>Anonymous</em></strong></a><div class="date" title="2014-03-08 11:42"><strong>5 months ago</strong></div>
  <div class="text" id="Hcom114582">
<div class="phpcode"><code><span class="html">
By default the stack trace is pretty unreadable, so you might want to wrap it in &lt;pre&gt; tags. Here I also wrap it in a &lt;div&gt; and set the class 'alert alert-danger' which are CSS classes in the Bootstrap CSS framework to style them red.<br><span class="default">&lt;?php<br><br></span><span class="keyword">function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br>&nbsp; echo </span><span class="string">'&lt;div class="alert alert-danger"&gt;'</span><span class="keyword">;<br>&nbsp; echo </span><span class="string">'&lt;b&gt;Fatal error&lt;/b&gt;:&nbsp; Uncaught exception \'' </span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) . </span><span class="string">'\' with message '</span><span class="keyword">;<br>&nbsp; echo </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() . </span><span class="string">'&lt;br&gt;'</span><span class="keyword">;<br>&nbsp; echo </span><span class="string">'Stack trace:&lt;pre&gt;' </span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">() . </span><span class="string">'&lt;/pre&gt;'</span><span class="keyword">;<br>&nbsp; echo </span><span class="string">'thrown in &lt;b&gt;' </span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getFile</span><span class="keyword">() . </span><span class="string">'&lt;/b&gt; on line &lt;b&gt;' </span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">() . </span><span class="string">'&lt;/b&gt;&lt;br&gt;'</span><span class="keyword">;<br>&nbsp; echo </span><span class="string">'&lt;/div&gt;'</span><span class="keyword">;<br>}<br><br></span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">'exception_handler'</span><span class="keyword">);</span>
</span>
</code></div>
  </div>
 </div>
  <div class="note" id="82512">  
  <a class="name">
  <strong class="user"><em>marques at displague dot com</em></strong></a><div class="date" title="2008-04-14 07:19"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom82512">
<div class="phpcode"><code><span class="html">
frank,<br><br>Your exception handler is configured to be the handler for all exceptions, yet if a basic 'Exception' is thrown, your static method will error because 'Exception's do not have 'getException'.&nbsp; Because of this I don't see a real purpose to making the uncaught handler a class that extends Exception.&nbsp; <br><br>I do like the idea of using static methods of a general Exception handling class.&nbsp; <br><br><span class="default">&lt;?php<br></span><span class="keyword">class </span><span class="default">ExceptionHandler </span><span class="keyword">{&nbsp;&nbsp; <br>&nbsp; &nbsp; public static function </span><span class="default">printException</span><span class="keyword">(</span><span class="default">Exception $e</span><span class="keyword">)<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; print </span><span class="string">'Uncaught '</span><span class="keyword">.</span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">).</span><span class="string">', code: ' </span><span class="keyword">. </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getCode</span><span class="keyword">() . </span><span class="string">"&lt;br /&gt;Message: " </span><span class="keyword">. </span><span class="default">htmlentities</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()).</span><span class="string">"\n"</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>&nbsp;&nbsp; <br>&nbsp; &nbsp; public static function </span><span class="default">handleException</span><span class="keyword">(</span><span class="default">Exception $e</span><span class="keyword">)<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">self</span><span class="keyword">::</span><span class="default">printException</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>}<br><br></span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="string">"ExceptionHandler"</span><span class="keyword">, </span><span class="string">"handleException"</span><span class="keyword">));<br><br>class </span><span class="default">NewException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{}<br>try {<br>&nbsp; throw new </span><span class="default">NewException</span><span class="keyword">(</span><span class="string">"Catch me once"</span><span class="keyword">, </span><span class="default">1</span><span class="keyword">);<br>} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br>&nbsp; </span><span class="default">ExceptionHandler</span><span class="keyword">::</span><span class="default">handleException</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">);<br>}<br><br>throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Catch me twice"</span><span class="keyword">, </span><span class="default">2</span><span class="keyword">);<br></span><span class="default">?&gt;<br></span><br>Gives:<br>Uncaught NewException, code: 1&lt;br /&gt;Message: Catch me once<br>Uncaught Exception, code: 2&lt;br /&gt;Message: Catch me twice<br><br>There are much more interesting things that can be done like reformating and optionally displaying or emailing them.&nbsp; But this class acts a nice container for those functions.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="76300">  
  <a class="name">
  <strong class="user"><em>parazuce at gmail dot com</em></strong></a><div class="date" title="2007-07-09 03:41"><strong>7 years ago</strong></div>
  <div class="text" id="Hcom76300">
<div class="phpcode"><code><span class="html">
I've been messing around with this function, and have noticed you can pass an anonymous function (created with create_function()) through as the default handler, for example:<br><br>set_exception_handler(create_function('$e', 'exit("An unknown error occurred");'));<br><br>That snippet of code can be used if you simply want to suppress all exceptions that are not handled.&nbsp; This can be a great thing, because secure data could possibly be leaked otherwise (for example, the default exception handler could output a snippet of your SQL code that was involved with the exception being thrown).<br><br>You will want to use this wisely, however (if at all).</span>
</code></div>
  </div>
 </div>
  <div class="note" id="64110">  
  <a class="name">
  <strong class="user"><em>mc-php-doco at oak dot homeunix dot org</em></strong></a><div class="date" title="2006-04-07 09:41"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom64110">
<div class="phpcode"><code><span class="html">
This seems not to work when calling the PHP binary with the '-r' flag.<br><br>For example, if I run it like this:<br><br>&nbsp; &nbsp; php -r '<br>&nbsp; &nbsp; &nbsp; function exception_handler($exception) {<br>&nbsp; &nbsp; &nbsp; &nbsp; echo "Uncaught exception: " , $exception-&gt;getMessage(), "\n";<br>&nbsp; &nbsp; &nbsp; }<br> <br>&nbsp; &nbsp; &nbsp; set_exception_handler("exception_handler");<br> <br>&nbsp; &nbsp; &nbsp; throw new Exception("Uncaught Exception");<br>&nbsp; &nbsp; &nbsp; echo "Not Executed\n";<br>&nbsp; &nbsp; '<br><br>Or if I place it in a file and run it like this:<br><br>&nbsp; &nbsp; php -r 'include "./tmp.php";'<br><br>I get a stack trace instead of having the function 'exception_handler' called.&nbsp; If run it like this:<br><br>&nbsp; &nbsp; php tmp.php<br><br>It works fine.&nbsp; <br><br>(Why run code from '-r'?&nbsp; Sometimes it's useful to add stuff around the include like calls to microtime for benchmarks, or to include a library and then call a few functions from the library, all in an ad-hoc way without having to create new files.)<br><br>PHP versions 5.1.2 and 5.0.4.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="111484">  
  <a class="name">
  <strong class="user"><em>Anonymous</em></strong></a><div class="date" title="2013-02-25 08:51"><strong>1 year ago</strong></div>
  <div class="text" id="Hcom111484">
<div class="phpcode"><code><span class="html">
As of PHP 5.4.11....
<br>
<br>Instead of:
<br>
<br>Output: Fatal error: Exception thrown without a stack frame in Unknown on line 0
<br>
<br>This snippet:
<br>
<br><span class="default">&lt;?php
<br></span><span class="keyword">function </span><span class="default">error_handler</span><span class="keyword">(</span><span class="default">$code</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">)
<br>{
<br>&nbsp; &nbsp; if (</span><span class="default">0 </span><span class="keyword">== </span><span class="default">error_reporting</span><span class="keyword">())
<br>&nbsp; &nbsp; {
<br>&nbsp; &nbsp; &nbsp; &nbsp; return;
<br>&nbsp; &nbsp; }
<br>&nbsp; &nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">);
<br>}
<br>function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">)
<br>{
<br>&nbsp; &nbsp; </span><span class="comment">// ... normal exception stuff goes here
<br>&nbsp; &nbsp; </span><span class="keyword">print </span><span class="default">$undefined</span><span class="keyword">; </span><span class="comment">// This is the underlying problem
<br></span><span class="keyword">}
<br></span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">"error_handler"</span><span class="keyword">);
<br></span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"exception_handler"</span><span class="keyword">);
<br>throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Just invoking the exception handler"</span><span class="keyword">);
<br></span><span class="default">?&gt;
<br></span>
<br>Now returns:
<br>
<br>Fatal error: Uncaught exception 'ErrorException' with message 'Undefined variable: undefined' in C:\Apache2\htdocs\error\test.php:13 Stack trace: #0 C:\Apache2\htdocs\error\test.php(13): error_handler(8, 'Undefined varia...', 'C:\Apache2\htdo...', 13, Array) #1 [internal function]: exception_handler(Object(Exception)) #2 {main} thrown in C:\Apache2\htdocs\error\test.php on line 13
<br>
<br>So it appears that exceptions thrown within exception handler now bypass exception handler.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="95054">  
  <a class="name">
  <strong class="user"><em>Anonymous</em></strong></a><div class="date" title="2009-12-10 06:09"><strong>4 years ago</strong></div>
  <div class="text" id="Hcom95054">
<div class="phpcode"><code><span class="html">
When an uncaught exception is handled, execution does NOT return to the script, but rather (unexpectedly, on my end anyway) terminates.<br><br>I am using set_error_handler() and set_exception_handler() in conjunction for a system I am currently developing (on v5.3.0 with Xampp). Lets say two E_USER_NOTICES are triggered, the script will die after the first one is processed.<br><br><span class="default">&lt;?php<br>&nbsp; &nbsp; set_exception_handler</span><span class="keyword">( </span><span class="string">'exc_handler' </span><span class="keyword">);<br>&nbsp; &nbsp; function </span><span class="default">exc_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp; &nbsp; echo </span><span class="string">"Uncaught exception: " </span><span class="keyword">, </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">(), </span><span class="string">"\n"</span><span class="keyword">;<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; function </span><span class="default">errorone</span><span class="keyword">() {<br>&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Test 1"</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; function </span><span class="default">errortwo</span><span class="keyword">() {<br>&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Test 2"</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; function </span><span class="default">test</span><span class="keyword">() {<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">errorone</span><span class="keyword">();<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">errortwo</span><span class="keyword">();<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; </span><span class="default">test</span><span class="keyword">();<br>&nbsp; &nbsp; </span><span class="default">test</span><span class="keyword">();<br></span><span class="default">?&gt;<br></span><br>Instead of printing (as I'd expect) "Uncaught exception: Text 1\nUncaught exception: Text 2\nUncaught exception: Text 1\nUncaught exception: Text 2\n"<br><br>It is only printed ONCE. I've tried a number of different things, but I can't figure out how to return execution to the script after the EXCEPTION HANDLER has run.<br><br>If anyone has a solution on how to return execution (hence, allow the script to log uncaught exceptions but continue processing) then PLEASE email me! Thanks!</span>
</code></div>
  </div>
 </div>
  <div class="note" id="78985">  
  <a class="name">
  <strong class="user"><em>frank at netventures dot com dot au</em></strong></a><div class="date" title="2007-11-05 10:10"><strong>6 years ago</strong></div>
  <div class="text" id="Hcom78985">
<div class="phpcode"><code><span class="html">
Hey all, i've just started to use the exception suite instead of the normal PHP error suite. For those of you looking for an object orientated way to do this without looking down at Glen and Sean's examples (Lesson 1: ALWAYS read the logs!), here you go:<br><br><span class="default">&lt;?php<br><br></span><span class="keyword">class </span><span class="default">NewException </span><span class="keyword">extends </span><span class="default">Exception<br></span><span class="keyword">{<br>&nbsp; &nbsp; public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">=</span><span class="default">NULL</span><span class="keyword">)<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; <br>&nbsp; &nbsp; public function </span><span class="default">__toString</span><span class="keyword">()<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; return </span><span class="string">"Code: " </span><span class="keyword">. </span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getCode</span><span class="keyword">() . </span><span class="string">"&lt;br /&gt;Message: " </span><span class="keyword">. </span><span class="default">htmlentities</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br>&nbsp; &nbsp; }<br>&nbsp; &nbsp; <br>&nbsp; &nbsp; public function </span><span class="default">getException</span><span class="keyword">()<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp; print </span><span class="default">$this</span><span class="keyword">; </span><span class="comment">// This will print the return from the above method __toString()<br>&nbsp; &nbsp; </span><span class="keyword">}<br>&nbsp; &nbsp; <br>&nbsp; &nbsp; public static function </span><span class="default">getStaticException</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">)<br>&nbsp; &nbsp; {<br>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getException</span><span class="keyword">(); </span><span class="comment">// $exception is an instance of this class<br>&nbsp; &nbsp; </span><span class="keyword">}<br>}<br><br></span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="string">"NewException"</span><span class="keyword">, </span><span class="string">"getStaticException"</span><span class="keyword">));<br>throw new </span><span class="default">NewException</span><span class="keyword">(</span><span class="string">"Catch me!!!"</span><span class="keyword">, </span><span class="default">69</span><span class="keyword">);<br><br></span><span class="default">?&gt;<br></span><br>Let me know if i'm missing something obvious as I left my glasses at home and I just came back from the Melbourne cup (If I won then I wouldn't be at work still!).</span>
</code></div>
  </div>
 </div>
  <div class="note" id="75035">  
  <a class="name">
  <strong class="user"><em>reg dot php dot manual at entropy dot ch</em></strong></a><div class="date" title="2007-05-09 06:59"><strong>7 years ago</strong></div>
  <div class="text" id="Hcom75035">
<div class="phpcode"><code><span class="html">
In my experience, the static keyword is crucial for error handlers which are methods of a class instead of free-standing functions.<br><br>&nbsp; &nbsp; static function exceptionHandler($exception)<br><br>works but <br><br>&nbsp; &nbsp; function exceptionHandler($exception)<br><br>doesn't and results in a "Fatal error: Exception thrown without a stack frame in Unknown on line 0" message.<br><br>"public" is optional as it is the default anyway (but it is probably clearer to write it explicitly).</span>
</code></div>
  </div>
 </div>
  <div class="note" id="73607">  
  <a class="name">
  <strong class="user"><em>Glen</em></strong></a><div class="date" title="2007-03-03 12:34"><strong>7 years ago</strong></div>
  <div class="text" id="Hcom73607">
<div class="phpcode"><code><span class="html">
If you want a class instance to handle the exception, this is how you do it :<br><br><span class="default">&lt;?php<br></span><span class="keyword">class </span><span class="default">example </span><span class="keyword">{<br>&nbsp;&nbsp; public function </span><span class="default">__construct</span><span class="keyword">() {<br>&nbsp; &nbsp; &nbsp;&nbsp; @</span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="default">$this</span><span class="keyword">, </span><span class="string">'exception_handler'</span><span class="keyword">));<br>&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'DOH!!'</span><span class="keyword">);<br>&nbsp;&nbsp; }<br><br>&nbsp;&nbsp; public function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br>&nbsp; &nbsp; &nbsp;&nbsp; print </span><span class="string">"Exception Caught: "</span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() .</span><span class="string">"\n"</span><span class="keyword">;<br>&nbsp;&nbsp; }<br>}<br><br></span><span class="default">$example </span><span class="keyword">= new </span><span class="default">example</span><span class="keyword">;<br><br></span><span class="default">?&gt;<br></span><br>See the first post (Sean's) for a static example.&nbsp; As Sean points out, the exception_handler function must be declared public.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="62154">  
  <a class="name">
  <strong class="user"><em>ch at westend dot com</em></strong></a><div class="date" title="2006-02-21 07:06"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom62154">
<div class="phpcode"><code><span class="html">
It seems that although the Exception contains a backtrace itself, the stack for the debug_backtrace() function is empty when entering an exception handler. This is very inconvinient. See bug #36477.</span>
</code></div>
  </div>
 </div>
  <div class="note" id="58086">  
  <a class="name">
  <strong class="user"><em>sean at seanodonnell dot com</em></strong></a><div class="date" title="2005-10-23 04:48"><strong>8 years ago</strong></div>
  <div class="text" id="Hcom58086">
<div class="phpcode"><code><span class="html">
Using the 'set_exception_handler' function within a class, the defined 'exception_handler' method must be declared as 'public' (preferrable 'public static' if you use the "array('example', 'exception_handler')" syntax). 
<br>
<br><span class="default">&lt;?php
<br></span><span class="keyword">class </span><span class="default">example </span><span class="keyword">{
<br>&nbsp; &nbsp; public function </span><span class="default">__construct</span><span class="keyword">() {
<br>&nbsp; &nbsp; &nbsp; &nbsp; @</span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="string">'example'</span><span class="keyword">, </span><span class="string">'exception_handler'</span><span class="keyword">));
<br>&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'DOH!!'</span><span class="keyword">);
<br>&nbsp; &nbsp; }
<br>
<br>&nbsp; &nbsp; public static function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {
<br>&nbsp; &nbsp; &nbsp; &nbsp; print </span><span class="string">"Exception Caught: "</span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() .</span><span class="string">"\n"</span><span class="keyword">;
<br>&nbsp; &nbsp; }
<br>}
<br>
<br></span><span class="default">$example </span><span class="keyword">= new </span><span class="default">example</span><span class="keyword">;
<br>
<br>echo </span><span class="string">"Not Executed\n"</span><span class="keyword">;
<br></span><span class="default">?&gt;</span> 
<br>
<br>Declaring the 'exception_handler' function as 'private' causes a FATAL ERROR.
<br>
<br>[derick: red. updated statement about static a bit]</span>
</code></div>
  </div>
 </div></div>

 
</section>    </section><!-- layout-content -->
        


  </div><!-- layout -->
         
  

    
 <!-- External and third party libraries. -->
 







<a id="toTop" href="javascript:;"><span id="toTopHover"></span><img width="40" height="40" alt="To Top" src="../../images/to-top%402x.png"></a>



<!-- Mirrored from php.net/manual/en/function.set-exception-handler.php by HTTrack Website Copier/3.x [XR&CO'2013], Thu, 28 Aug 2014 15:28:44 GMT -->


</body></html>